import '../../models/enums.dart';
import '../../models/leaderboard_info.dart';

const kgLeaderboards = <LeaderboardSummary>[
  LeaderboardSummary(
    id: 'kg__8888',
    boardId: '8888',
    name: 'TOP500',
    source: MusicSource.kg,
  ),
  LeaderboardSummary(
    id: 'kg__6666',
    boardId: '6666',
    name: '飙升榜',
    source: MusicSource.kg,
  ),
  LeaderboardSummary(
    id: 'kg__59703',
    boardId: '59703',
    name: '蜂鸟流行音乐榜',
    source: MusicSource.kg,
  ),
  LeaderboardSummary(
    id: 'kg__52144',
    boardId: '52144',
    name: '抖音热歌榜',
    source: MusicSource.kg,
  ),
  LeaderboardSummary(
    id: 'kg__52767',
    boardId: '52767',
    name: '快手热歌榜',
    source: MusicSource.kg,
  ),
  LeaderboardSummary(
    id: 'kg__24971',
    boardId: '24971',
    name: 'DJ热歌榜',
    source: MusicSource.kg,
  ),
  LeaderboardSummary(
    id: 'kg__23784',
    boardId: '23784',
    name: '网络红歌榜',
    source: MusicSource.kg,
  ),
  LeaderboardSummary(
    id: 'kg__44412',
    boardId: '44412',
    name: '说唱先锋榜',
    source: MusicSource.kg,
  ),
  LeaderboardSummary(
    id: 'kg__31308',
    boardId: '31308',
    name: '内地榜',
    source: MusicSource.kg,
  ),
  LeaderboardSummary(
    id: 'kg__33160',
    boardId: '33160',
    name: '电音榜',
    source: MusicSource.kg,
  ),
  LeaderboardSummary(
    id: 'kg__31313',
    boardId: '31313',
    name: '香港地区榜',
    source: MusicSource.kg,
  ),
  LeaderboardSummary(
    id: 'kg__51341',
    boardId: '51341',
    name: '民谣榜',
    source: MusicSource.kg,
  ),
  LeaderboardSummary(
    id: 'kg__54848',
    boardId: '54848',
    name: '台湾地区榜',
    source: MusicSource.kg,
  ),
  LeaderboardSummary(
    id: 'kg__31310',
    boardId: '31310',
    name: '欧美榜',
    source: MusicSource.kg,
  ),
  LeaderboardSummary(
    id: 'kg__33162',
    boardId: '33162',
    name: 'ACG新歌榜',
    source: MusicSource.kg,
  ),
  LeaderboardSummary(
    id: 'kg__31311',
    boardId: '31311',
    name: '韩国榜',
    source: MusicSource.kg,
  ),
  LeaderboardSummary(
    id: 'kg__31312',
    boardId: '31312',
    name: '日本榜',
    source: MusicSource.kg,
  ),
  LeaderboardSummary(
    id: 'kg__49225',
    boardId: '49225',
    name: '80后热歌榜',
    source: MusicSource.kg,
  ),
  LeaderboardSummary(
    id: 'kg__49223',
    boardId: '49223',
    name: '90后热歌榜',
    source: MusicSource.kg,
  ),
  LeaderboardSummary(
    id: 'kg__49224',
    boardId: '49224',
    name: '00后热歌榜',
    source: MusicSource.kg,
  ),
  LeaderboardSummary(
    id: 'kg__33165',
    boardId: '33165',
    name: '粤语金曲榜',
    source: MusicSource.kg,
  ),
  LeaderboardSummary(
    id: 'kg__33166',
    boardId: '33166',
    name: '欧美金曲榜',
    source: MusicSource.kg,
  ),
  LeaderboardSummary(
    id: 'kg__33163',
    boardId: '33163',
    name: '影视金曲榜',
    source: MusicSource.kg,
  ),
  LeaderboardSummary(
    id: 'kg__51340',
    boardId: '51340',
    name: '伤感榜',
    source: MusicSource.kg,
  ),
  LeaderboardSummary(
    id: 'kg__35811',
    boardId: '35811',
    name: '会员专享榜',
    source: MusicSource.kg,
  ),
  LeaderboardSummary(
    id: 'kg__37361',
    boardId: '37361',
    name: '雷达榜',
    source: MusicSource.kg,
  ),
  LeaderboardSummary(
    id: 'kg__21101',
    boardId: '21101',
    name: '分享榜',
    source: MusicSource.kg,
  ),
  LeaderboardSummary(
    id: 'kg__46910',
    boardId: '46910',
    name: '综艺新歌榜',
    source: MusicSource.kg,
  ),
  LeaderboardSummary(
    id: 'kg__30972',
    boardId: '30972',
    name: '酷狗音乐人原创榜',
    source: MusicSource.kg,
  ),
  LeaderboardSummary(
    id: 'kg__60170',
    boardId: '60170',
    name: '闽南语榜',
    source: MusicSource.kg,
  ),
  LeaderboardSummary(
    id: 'kg__65234',
    boardId: '65234',
    name: '儿歌榜',
    source: MusicSource.kg,
  ),
  LeaderboardSummary(
    id: 'kg__4681',
    boardId: '4681',
    name: '美国BillBoard榜',
    source: MusicSource.kg,
  ),
  LeaderboardSummary(
    id: 'kg__25028',
    boardId: '25028',
    name: 'Beatport电子舞曲榜',
    source: MusicSource.kg,
  ),
  LeaderboardSummary(
    id: 'kg__4680',
    boardId: '4680',
    name: '英国单曲榜',
    source: MusicSource.kg,
  ),
  LeaderboardSummary(
    id: 'kg__38623',
    boardId: '38623',
    name: '韩国Melon音乐榜',
    source: MusicSource.kg,
  ),
  LeaderboardSummary(
    id: 'kg__42807',
    boardId: '42807',
    name: 'joox本地热歌榜',
    source: MusicSource.kg,
  ),
  LeaderboardSummary(
    id: 'kg__36107',
    boardId: '36107',
    name: '小语种热歌榜',
    source: MusicSource.kg,
  ),
  LeaderboardSummary(
    id: 'kg__4673',
    boardId: '4673',
    name: '日本公信榜',
    source: MusicSource.kg,
  ),
  LeaderboardSummary(
    id: 'kg__46868',
    boardId: '46868',
    name: '日本SPACE SHOWER榜',
    source: MusicSource.kg,
  ),
  LeaderboardSummary(
    id: 'kg__42808',
    boardId: '42808',
    name: 'KKBOX风云榜',
    source: MusicSource.kg,
  ),
  LeaderboardSummary(
    id: 'kg__60171',
    boardId: '60171',
    name: '越南语榜',
    source: MusicSource.kg,
  ),
  LeaderboardSummary(
    id: 'kg__60172',
    boardId: '60172',
    name: '泰语榜',
    source: MusicSource.kg,
  ),
  LeaderboardSummary(
    id: 'kg__59895',
    boardId: '59895',
    name: 'R&B榜',
    source: MusicSource.kg,
  ),
  LeaderboardSummary(
    id: 'kg__59896',
    boardId: '59896',
    name: '摇滚榜',
    source: MusicSource.kg,
  ),
  LeaderboardSummary(
    id: 'kg__59897',
    boardId: '59897',
    name: '爵士榜',
    source: MusicSource.kg,
  ),
  LeaderboardSummary(
    id: 'kg__59898',
    boardId: '59898',
    name: '乡村音乐榜',
    source: MusicSource.kg,
  ),
  LeaderboardSummary(
    id: 'kg__59900',
    boardId: '59900',
    name: '纯音乐榜',
    source: MusicSource.kg,
  ),
  LeaderboardSummary(
    id: 'kg__59899',
    boardId: '59899',
    name: '古典榜',
    source: MusicSource.kg,
  ),
  LeaderboardSummary(
    id: 'kg__22603',
    boardId: '22603',
    name: '5sing音乐榜',
    source: MusicSource.kg,
  ),
  LeaderboardSummary(
    id: 'kg__21335',
    boardId: '21335',
    name: '繁星音乐榜',
    source: MusicSource.kg,
  ),
  LeaderboardSummary(
    id: 'kg__33161',
    boardId: '33161',
    name: '古风新歌榜',
    source: MusicSource.kg,
  ),
];
