import '../../models/enums.dart';
import '../../models/leaderboard_info.dart';

const kwLeaderboards = <LeaderboardSummary>[
  LeaderboardSummary(
    id: 'kw__93',
    boardId: '93',
    name: '飙升榜',
    source: MusicSource.kw,
  ),
  LeaderboardSummary(
    id: 'kw__17',
    boardId: '17',
    name: '新歌榜',
    source: MusicSource.kw,
  ),
  LeaderboardSummary(
    id: 'kw__16',
    boardId: '16',
    name: '热歌榜',
    source: MusicSource.kw,
  ),
  LeaderboardSummary(
    id: 'kw__158',
    boardId: '158',
    name: '抖音热歌榜',
    source: MusicSource.kw,
  ),
  LeaderboardSummary(
    id: 'kw__292',
    boardId: '292',
    name: '铃声榜',
    source: MusicSource.kw,
  ),
  LeaderboardSummary(
    id: 'kw__284',
    boardId: '284',
    name: '热评榜',
    source: MusicSource.kw,
  ),
  LeaderboardSummary(
    id: 'kw__290',
    boardId: '290',
    name: 'ACG新歌榜',
    source: MusicSource.kw,
  ),
  LeaderboardSummary(
    id: 'kw__286',
    boardId: '286',
    name: '台湾KKBOX榜',
    source: MusicSource.kw,
  ),
  LeaderboardSummary(
    id: 'kw__279',
    boardId: '279',
    name: '冬日暖心榜',
    source: MusicSource.kw,
  ),
  LeaderboardSummary(
    id: 'kw__281',
    boardId: '281',
    name: '巴士随身听榜',
    source: MusicSource.kw,
  ),
  LeaderboardSummary(
    id: 'kw__255',
    boardId: '255',
    name: 'KTV点唱榜',
    source: MusicSource.kw,
  ),
  LeaderboardSummary(
    id: 'kw__280',
    boardId: '280',
    name: '家务进行曲榜',
    source: MusicSource.kw,
  ),
  LeaderboardSummary(
    id: 'kw__282',
    boardId: '282',
    name: '熬夜修仙榜',
    source: MusicSource.kw,
  ),
  LeaderboardSummary(
    id: 'kw__283',
    boardId: '283',
    name: '枕边轻音乐榜',
    source: MusicSource.kw,
  ),
  LeaderboardSummary(
    id: 'kw__278',
    boardId: '278',
    name: '古风音乐榜',
    source: MusicSource.kw,
  ),
  LeaderboardSummary(
    id: 'kw__264',
    boardId: '264',
    name: 'Vlog音乐榜',
    source: MusicSource.kw,
  ),
  LeaderboardSummary(
    id: 'kw__242',
    boardId: '242',
    name: '电音榜',
    source: MusicSource.kw,
  ),
  LeaderboardSummary(
    id: 'kw__187',
    boardId: '187',
    name: '流行趋势榜',
    source: MusicSource.kw,
  ),
  LeaderboardSummary(
    id: 'kw__204',
    boardId: '204',
    name: '现场音乐榜',
    source: MusicSource.kw,
  ),
  LeaderboardSummary(
    id: 'kw__186',
    boardId: '186',
    name: 'ACG神曲榜',
    source: MusicSource.kw,
  ),
  LeaderboardSummary(
    id: 'kw__185',
    boardId: '185',
    name: '最强翻唱榜',
    source: MusicSource.kw,
  ),
  LeaderboardSummary(
    id: 'kw__26',
    boardId: '26',
    name: '经典怀旧榜',
    source: MusicSource.kw,
  ),
  LeaderboardSummary(
    id: 'kw__104',
    boardId: '104',
    name: '华语榜',
    source: MusicSource.kw,
  ),
  LeaderboardSummary(
    id: 'kw__182',
    boardId: '182',
    name: '粤语榜',
    source: MusicSource.kw,
  ),
  LeaderboardSummary(
    id: 'kw__22',
    boardId: '22',
    name: '欧美榜',
    source: MusicSource.kw,
  ),
  LeaderboardSummary(
    id: 'kw__184',
    boardId: '184',
    name: '韩语榜',
    source: MusicSource.kw,
  ),
  LeaderboardSummary(
    id: 'kw__183',
    boardId: '183',
    name: '日语榜',
    source: MusicSource.kw,
  ),
  LeaderboardSummary(
    id: 'kw__145',
    boardId: '145',
    name: '会员畅听榜',
    source: MusicSource.kw,
  ),
  LeaderboardSummary(
    id: 'kw__153',
    boardId: '153',
    name: '网红新歌榜',
    source: MusicSource.kw,
  ),
  LeaderboardSummary(
    id: 'kw__64',
    boardId: '64',
    name: '影视金曲榜',
    source: MusicSource.kw,
  ),
  LeaderboardSummary(
    id: 'kw__176',
    boardId: '176',
    name: 'DJ嗨歌榜',
    source: MusicSource.kw,
  ),
  LeaderboardSummary(
    id: 'kw__106',
    boardId: '106',
    name: '真声音',
    source: MusicSource.kw,
  ),
  LeaderboardSummary(
    id: 'kw__12',
    boardId: '12',
    name: 'Billboard榜',
    source: MusicSource.kw,
  ),
  LeaderboardSummary(
    id: 'kw__49',
    boardId: '49',
    name: 'iTunes音乐榜',
    source: MusicSource.kw,
  ),
  LeaderboardSummary(
    id: 'kw__180',
    boardId: '180',
    name: 'beatport电音榜',
    source: MusicSource.kw,
  ),
  LeaderboardSummary(
    id: 'kw__13',
    boardId: '13',
    name: '英国UK榜',
    source: MusicSource.kw,
  ),
  LeaderboardSummary(
    id: 'kw__164',
    boardId: '164',
    name: '百大DJ榜',
    source: MusicSource.kw,
  ),
  LeaderboardSummary(
    id: 'kw__246',
    boardId: '246',
    name: 'YouTube音乐排行榜',
    source: MusicSource.kw,
  ),
  LeaderboardSummary(
    id: 'kw__265',
    boardId: '265',
    name: '韩国Genie榜',
    source: MusicSource.kw,
  ),
  LeaderboardSummary(
    id: 'kw__14',
    boardId: '14',
    name: '韩国M-net榜',
    source: MusicSource.kw,
  ),
  LeaderboardSummary(
    id: 'kw__8',
    boardId: '8',
    name: '香港电台榜',
    source: MusicSource.kw,
  ),
  LeaderboardSummary(
    id: 'kw__15',
    boardId: '15',
    name: '日本公信榜',
    source: MusicSource.kw,
  ),
  LeaderboardSummary(
    id: 'kw__151',
    boardId: '151',
    name: '腾讯音乐人原创榜',
    source: MusicSource.kw,
  ),
];
